"""Run cancellation (Phase 16).

A small directory — `.orchestrator/cancellations/` — holds one empty
marker file per cancelled thread_id. Existence of the marker IS the
cancel signal. The workflow body in workflow.py checks for the marker
between @task boundaries and raises `WorkflowCancelled` when its
thread_id's marker is present; the entrypoint catches the exception
and returns a "cancelled" status dict.

Why a filesystem marker rather than a SQLite table or custom
checkpointer state:
  - Zero contention. The LangGraph AsyncSqliteSaver holds a write
    lock on `checkpoints.db` for the duration of the workflow. A
    synchronous sqlite3 connection from a second module hits
    "database is locked" intermittently. A filesystem marker has no
    such coupling.
  - Survives LangGraph schema changes. The marker is ours; the
    checkpoint schema is LangGraph's.
  - Writable WITHOUT loading or stepping the workflow — the
    cancel_run MCP tool fires against a thread that the orchestrator
    is not currently running.
  - Trivially atomic. touch() and unlink() are single syscalls;
    is-file is a stat call.

Semantics: the cancel check sits between tasks, NOT inside an
in-flight LLM call. The currently running task completes before the
next check fires — so the spent tokens are not refunded. "Cancel"
means "stop after the current task," not "abort instantly." Streaming
cancellation propagated to the Anthropic SDK would be a much larger
piece of work.
"""

import re
from pathlib import Path

from orchestrator.config import load_config
from orchestrator.paths import find_project_root


class WorkflowCancelled(Exception):
    """Raised between tasks when the workflow's thread_id has been
    marked cancelled. The workflow entrypoint catches this and
    converts it into a status="cancelled" return dict."""


# Thread ids are generated by mcp_server.implement_feature as
# `run-<8 hex chars>`. We accept the broader pattern of letters,
# digits, hyphen, and underscore here so callers can pass any
# orchestrator-generated id without us second-guessing the format,
# but we reject path-traversal characters so a malicious or buggy
# caller can't write outside the cancellations directory.
_THREAD_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def _validate_thread_id(thread_id: str) -> None:
    if not _THREAD_ID_RE.fullmatch(thread_id):
        raise ValueError(
            f"thread_id {thread_id!r} contains characters outside "
            "[A-Za-z0-9_-]; refusing to use as a filename."
        )


def _cancellations_dir(base_dir: Path | None = None) -> Path:
    """Resolve the directory holding cancellation marker files.

    Defaults to `<config.db_path's parent>/cancellations` so the
    markers sit alongside the LangGraph checkpoint db. Callers can
    pass an explicit base_dir for tests.
    """
    if base_dir is not None:
        return base_dir
    config = load_config()
    db_parent = Path(config.db_path).parent
    relative = db_parent / "cancellations"
    return relative if relative.is_absolute() else find_project_root() / relative


def _marker(thread_id: str, base_dir: Path | None = None) -> Path:
    _validate_thread_id(thread_id)
    return _cancellations_dir(base_dir) / thread_id


def mark_cancelled(thread_id: str, base_dir: Path | None = None) -> None:
    """Signal cancellation for `thread_id`. Idempotent."""
    marker = _marker(thread_id, base_dir)
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.touch(exist_ok=True)


def is_cancelled(thread_id: str, base_dir: Path | None = None) -> bool:
    """Return True if `thread_id` has been signalled for cancellation."""
    return _marker(thread_id, base_dir).exists()


def clear_cancelled(thread_id: str, base_dir: Path | None = None) -> None:
    """Remove the cancel marker for `thread_id`. Used by force-resume."""
    _marker(thread_id, base_dir).unlink(missing_ok=True)


def raise_if_cancelled(thread_id: str, base_dir: Path | None = None) -> None:
    """Raise WorkflowCancelled if the thread is marked cancelled.

    The single call site every workflow checkpoint uses. Keeping the
    check in one helper means we can later add (e.g.) logging or
    metrics without touching the workflow body.
    """
    if is_cancelled(thread_id, base_dir):
        raise WorkflowCancelled(thread_id)
